version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: my_project-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7.4
    container_name: my_project-redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    container_name: my_project-app
    environment:
      DATABASE_URL: "mysql+aiomysql://user:password@db/yourdatabase"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

volumes:
  mysql_data: {}
